# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: OTc5NzE4YmNiNjc5MmFkNWY0YzA3MGFlODcyYTUyMGRkYzM3MDc0ZDhhZjM1NTc3ODY3ODc5N2Y5MzMzNGI0MDlmMmI2OTgwMWE2YWViNmI2OWUyZmU2ZTU2ZDM0MTEyZWUwODYwNjU0ZDYwMzczN2NmZmMwYTk4OGQ1MTRhYmU=
