# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZmI2NGUyNzc0OWUzYzhlNzNiNDE2MmNlYWNkZTg2ODkzYmEyN2QwYzYxZTcyNGYzNTc2YTI5ZWUzMGU2YWNmZTVlYmQxOWMzYjNmNjUxNTkzYTYzYzY0NDA2YTdhYmE3OWY1MDkyYzUzYzYyNjI5YTUyYTVhYzRhNDdhZTQ4MDU=
