package com.edu.sena.zentry.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UsuarioConjuntoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUsuarioConjuntoAllPropertiesEquals(UsuarioConjunto expected, UsuarioConjunto actual) {
        assertUsuarioConjuntoAutoGeneratedPropertiesEquals(expected, actual);
        assertUsuarioConjuntoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUsuarioConjuntoAllUpdatablePropertiesEquals(UsuarioConjunto expected, UsuarioConjunto actual) {
        assertUsuarioConjuntoUpdatableFieldsEquals(expected, actual);
        assertUsuarioConjuntoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUsuarioConjuntoAutoGeneratedPropertiesEquals(UsuarioConjunto expected, UsuarioConjunto actual) {
        assertThat(actual)
            .as("Verify UsuarioConjunto auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUsuarioConjuntoUpdatableFieldsEquals(UsuarioConjunto expected, UsuarioConjunto actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUsuarioConjuntoUpdatableRelationshipsEquals(UsuarioConjunto expected, UsuarioConjunto actual) {
        assertThat(actual)
            .as("Verify UsuarioConjunto relationships")
            .satisfies(a ->
                assertThat(a.getConjuntoResidencial()).as("check conjuntoResidencial").isEqualTo(expected.getConjuntoResidencial())
            );
    }
}
